// website/src/pages/examples/LoginForm.tsx
import { Link } from 'react-router-dom'
import { ArrowLeft, ExternalLink } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { CodeBlock } from '@/components/code/CodeBlock'
import { BrowserWindow } from '@/components/code/BrowserWindow'

const loginFormCode = `import { useForm, useField, FormProvider } from '@oxog/formkeeper/react'

interface LoginValues {
  email: string
  password: string
}

export function LoginForm() {
  const form = useForm<LoginValues>({
    initialValues: {
      email: '',
      password: '',
    },
    onSubmit: async (values) => {
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1000))
      console.log('Login successful:', values)
      alert('Login successful!')
    },
  })

  return (
    <FormProvider form={form}>
      <form
        onSubmit={form.handleSubmit}
        className="max-w-md mx-auto p-6 space-y-4"
      >
        <h2 className="text-2xl font-bold text-center mb-6">Login</h2>

        <EmailField />
        <PasswordField />

        <button
          type="submit"
          disabled={form.formState.isSubmitting}
          className="w-full py-2 px-4 bg-blue-600 text-white rounded-md
                     hover:bg-blue-700 disabled:opacity-50"
        >
          {form.formState.isSubmitting ? 'Logging in...' : 'Login'}
        </button>
      </form>
    </FormProvider>
  )
}

function EmailField() {
  const { register, error, touched } = useField('email', {
    required: 'Email is required',
    pattern: {
      value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}$/i,
      message: 'Invalid email address',
    },
  })

  return (
    <div className="space-y-1">
      <label htmlFor="email" className="block text-sm font-medium">
        Email
      </label>
      <input
        {...register()}
        type="email"
        id="email"
        placeholder="you@example.com"
        className="w-full px-3 py-2 border rounded-md focus:outline-none
                   focus:ring-2 focus:ring-blue-500"
      />
      {touched && error && (
        <p className="text-sm text-red-500">{error}</p>
      )}
    </div>
  )
}

function PasswordField() {
  const { register, error, touched } = useField('password', {
    required: 'Password is required',
    minLength: {
      value: 8,
      message: 'Password must be at least 8 characters',
    },
  })

  return (
    <div className="space-y-1">
      <label htmlFor="password" className="block text-sm font-medium">
        Password
      </label>
      <input
        {...register()}
        type="password"
        id="password"
        placeholder="********"
        className="w-full px-3 py-2 border rounded-md focus:outline-none
                   focus:ring-2 focus:ring-blue-500"
      />
      {touched && error && (
        <p className="text-sm text-red-500">{error}</p>
      )}
    </div>
  )
}`

export function LoginFormExample() {
  return (
    <div className="container py-12 max-w-5xl">
      <div className="mb-8">
        <Button variant="ghost" asChild className="mb-4">
          <Link to="/examples">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Examples
          </Link>
        </Button>

        <h1 className="text-4xl font-bold mb-4">Login Form</h1>
        <p className="text-lg text-muted-foreground">
          A basic login form with email and password validation. This example
          demonstrates the core FormKeeper API for handling simple forms.
        </p>
      </div>

      {/* Preview */}
      <section className="mb-12">
        <h2 className="text-2xl font-semibold mb-4">Preview</h2>
        <BrowserWindow url="localhost:3000/login">
          <div className="p-8 bg-white dark:bg-zinc-900">
            <div className="max-w-md mx-auto p-6 border rounded-lg">
              <h2 className="text-2xl font-bold text-center mb-6">Login</h2>
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium mb-1">Email</label>
                  <input
                    type="email"
                    placeholder="you@example.com"
                    className="w-full px-3 py-2 border rounded-md bg-background"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1">Password</label>
                  <input
                    type="password"
                    placeholder="********"
                    className="w-full px-3 py-2 border rounded-md bg-background"
                  />
                </div>
                <button className="w-full py-2 px-4 bg-blue-600 text-white rounded-md hover:bg-blue-700">
                  Login
                </button>
              </div>
            </div>
          </div>
        </BrowserWindow>
      </section>

      {/* Source Code */}
      <section className="mb-12">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-2xl font-semibold">Source Code</h2>
          <Button variant="outline" size="sm" asChild>
            <Link to="/playground">
              Open in Playground
              <ExternalLink className="w-4 h-4 ml-2" />
            </Link>
          </Button>
        </div>
        <CodeBlock
          code={loginFormCode}
          language="tsx"
          filename="LoginForm.tsx"
        />
      </section>

      {/* Key Concepts */}
      <section>
        <h2 className="text-2xl font-semibold mb-4">Key Concepts</h2>
        <ul className="space-y-3">
          <li className="flex gap-3">
            <div className="w-2 h-2 rounded-full bg-primary mt-2" />
            <div>
              <strong>useForm</strong> - Creates a form instance with initial
              values and submit handler
            </div>
          </li>
          <li className="flex gap-3">
            <div className="w-2 h-2 rounded-full bg-primary mt-2" />
            <div>
              <strong>useField</strong> - Registers a field with validation rules
              and returns field state
            </div>
          </li>
          <li className="flex gap-3">
            <div className="w-2 h-2 rounded-full bg-primary mt-2" />
            <div>
              <strong>FormProvider</strong> - Provides form context to child
              components
            </div>
          </li>
          <li className="flex gap-3">
            <div className="w-2 h-2 rounded-full bg-primary mt-2" />
            <div>
              <strong>register()</strong> - Returns props to spread on input
              elements
            </div>
          </li>
          <li className="flex gap-3">
            <div className="w-2 h-2 rounded-full bg-primary mt-2" />
            <div>
              <strong>touched & error</strong> - Shows errors only after user
              interacts with field
            </div>
          </li>
        </ul>
      </section>
    </div>
  )
}

// examples/vue/login-form/LoginForm.vue
<script setup lang="ts">
/**
 * Vue Login Form Example
 *
 * This example demonstrates a basic login form with FormKeeper's Vue adapter.
 *
 * Features:
 * - Field registration with validation rules
 * - Reactive form state
 * - Error display on blur
 * - Form submission handling
 */

import { useForm, useField } from '@oxog/formkeeper/vue'

interface LoginValues {
  email: string
  password: string
  remember: boolean
}

const form = useForm<LoginValues>({
  initialValues: {
    email: '',
    password: '',
    remember: false,
  },
  mode: 'onBlur',
  onSubmit: async (values) => {
    // Simulate API call
    await new Promise((resolve) => setTimeout(resolve, 1000))
    console.log('Login submitted:', values)
    alert('Login successful!')
  },
})

// Email field
const emailField = useField('email', {
  required: 'Email is required',
  pattern: {
    value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    message: 'Please enter a valid email address',
  },
})

// Password field
const passwordField = useField('password', {
  required: 'Password is required',
  minLength: {
    value: 6,
    message: 'Password must be at least 6 characters',
  },
})

// Remember me field
const rememberField = useField('remember')
</script>

<template>
  <form @submit.prevent="form.handleSubmit" class="login-form">
    <h1>Login</h1>

    <!-- Email Field -->
    <div class="form-group">
      <label for="email">Email</label>
      <input
        v-bind="emailField.register()"
        type="email"
        id="email"
        placeholder="Enter your email"
        :class="{ error: emailField.touched && emailField.error }"
      />
      <span v-if="emailField.touched && emailField.error" class="error-message">
        {{ emailField.error }}
      </span>
    </div>

    <!-- Password Field -->
    <div class="form-group">
      <label for="password">Password</label>
      <input
        v-bind="passwordField.register()"
        type="password"
        id="password"
        placeholder="Enter your password"
        :class="{ error: passwordField.touched && passwordField.error }"
      />
      <span v-if="passwordField.touched && passwordField.error" class="error-message">
        {{ passwordField.error }}
      </span>
    </div>

    <!-- Remember Me -->
    <div class="form-group checkbox">
      <label>
        <input v-bind="rememberField.register()" type="checkbox" />
        Remember me
      </label>
    </div>

    <!-- Submit Button -->
    <button
      type="submit"
      :disabled="form.isSubmitting"
      class="submit-button"
    >
      {{ form.isSubmitting ? 'Logging in...' : 'Login' }}
    </button>

    <p class="signup-link">
      Don't have an account? <a href="/signup">Sign up</a>
    </p>
  </form>
</template>

<style scoped>
.login-form {
  max-width: 400px;
  margin: 0 auto;
  padding: 2rem;
}

h1 {
  margin-bottom: 1.5rem;
  text-align: center;
}

.form-group {
  margin-bottom: 1rem;
}

label {
  display: block;
  margin-bottom: 0.5rem;
  font-size: 0.875rem;
}

input[type="email"],
input[type="password"] {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #27272a;
  border-radius: 0.5rem;
  background: #18181b;
  color: #fafafa;
}

input:focus {
  outline: none;
  border-color: #3b82f6;
}

input.error {
  border-color: #ef4444;
}

.error-message {
  color: #ef4444;
  font-size: 0.75rem;
  margin-top: 0.25rem;
  display: block;
}

.checkbox label {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  cursor: pointer;
}

.submit-button {
  width: 100%;
  padding: 0.75rem;
  background: #3b82f6;
  color: white;
  border: none;
  border-radius: 0.5rem;
  cursor: pointer;
  font-size: 1rem;
  margin-top: 1rem;
}

.submit-button:hover {
  background: #2563eb;
}

.submit-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.signup-link {
  text-align: center;
  margin-top: 1rem;
  color: #a1a1aa;
}

.signup-link a {
  color: #3b82f6;
}
</style>
